GET http://localhost:3003/api/blogs


###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "The seven habits of highly effective people",
  "author": "Stephen Covey",
  "url": "www.google.com",
  "likes": 12
}

###
DELETE http://localhost:3003/api/blogs/6295f7b755e2d0d131635925

###
PUT http://localhost:3003/api/blogs/629a86b2740f488b09a29c4d
Content-Type: application/json

{
  "title": "The nine habits of highly effective people",
  "author": "Stephen Covey",
  "url": "www.google.com",
  "likes": 44,
  "other": "irrelevant",
  "stuff": "to be ignored..."
}