GET http://localhost:3001/api/diagnoses

###
GET http://localhost:3001/api/patients


###
GET http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667

###
POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "danny boy",
  "dateOfBirth": "1986-02-10",
  "gender": "male",
  "occupation": "teacher",
  "ssn": "3331234123"
}

###
POST http://localhost:3001/api/patients/d2773c6e-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "date": "2027-01-02", 
  "description": "rickets",
  "specialist": "auld manny rickets",
  "type": "HealthCheck",
  "employerName": "provo",
  "diagnosisCodes": ["2", "HC3"],
  "healthCheckRating": 3
}

###
POST http://localhost:3001/api/patients/d2773c6e-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "date": "2027-01-03", 
  "description": "bloat",
  "specialist": "auld manny rickets",
  "type": "Hospital",
  "diagnosisCodes": ["3", "HC4"],
  "discharge": {"date": "2027-02-01", "criteria": "has resolved"}
}