GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/2

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Albert Einstein",
    "number": "384-2831234322343321184"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "384-283-1184"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "broma"
}

###
GET http://localhost:3001/nonexistent


###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "asdfdssadfdsasdewq",
    "number": "23-48299-93423"
}


###
GET https://helsinki-fullstack-phonebook.herokuapp.com/api/persons


###
POST https://helsinki-fullstack-phonebook.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "asdfdssadfdsasdewq",
    "number": "23-4829993423"
}