###
GET http://localhost:3000/api/blogs

###
POST http://localhost:3000/api/blogs
Content-Type: application/json

{
  "author": "Matt Yglesias",
  "url": "https://www.slowboring.com/p/bidens-foreign-policy-disappointment",
  "title": "Biden's foreign policy disappointment",
  "likes": 136
}

###
DELETE http://localhost:3000/api/blogs/3

###
PUT http://localhost:3000/api/blogs/4
Content-Type: application/json

{
  "likes": 195
}