########## BLOGS ##########
###
GET http://localhost:3000/api/blogs

###
GET http://localhost:3000/api/blogs?search=is

###
POST http://localhost:3000/api/blogs
Content-Type: application/json

{
  "author": "Matt Yglesias",
  "url": "https://www.slowboring.com/p/bidens-foreign-policy-disappointment",
  "title": "Biden's foreign policy disappointment",
  "likes": 136
}

###
DELETE http://localhost:3000/api/blogs/3

###
PUT http://localhost:3000/api/blogs/4
Content-Type: application/json

{
  "likes": 195
}

### Invalid request - POST missing required fields
POST http://localhost:3000/api/blogs
Content-Type: application/json

{
  "author": "This has an author",
  "url": "And a URL, but no title",
  "likes": 136
}

### Invalid request - PUT missing 'likes'
PUT http://localhost:3000/api/blogs/4
Content-Type: application/json

{
  "author": "Nobody"
}

### Invalid request - likes should be a number
PUT http://localhost:3000/api/blogs/4
Content-Type: application/json

{
  "likes": "Yes, I do!"
}


###
POST http://localhost:3000/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJ1c2VyMkBleGFtcGxlLmNvbSIsImlhdCI6MTczMDI5NTkyM30.7Nq_bYmuL2hqb6ijAwyXsl_8mAlNbjLUvBBIUq2TlSY

{
  "author": "Matt Yglesias",
  "url": "https://www.slowboring.com/p/i-changed-my-mind",
  "title": "I changed my mind",
  "likes": 90,
  "year": 2024
}

