###
GET http://localhost:3001/api/ping


###
GET http://localhost:3001/api/diagnoses

###
GET http://localhost:3001/api/patients

###
POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "David Brent",
  "dateOfBirth": "1982-07-11",
  "gender": "male",
  "occupation": "Office General Manager",
  "ssn": "11111111"
}

###
GET http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667