###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "title2",
  "author": "name2",
  "url": "url2",
  "likes": "19"
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "root",
  "password": "opensesame",
  "name": "David Brent"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "example",
  "password": "pw1",
  "name": "Amy Smith"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "pi",
  "password": "pw1",
  "name": "Bella Ching"
}