#********BLOGS********
### GET all blogs
GET http://localhost:3003/api/blogs

### POST a new blog
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YmI2NmQyMTU2MjJkNDZlOWFhNjBiOSIsInVzZXJuYW1lIjoicm9vdCIsImlhdCI6MTcyMzY1NDYxMH0.ZvqrEUbrKz8_7NW9IGOr5YqsDvl52jy18n6Roub1Dgo

{
  "title": "random",
  "author": "random",
  "url": "random",
  "likes": "19"
}

#********USERS********
### GET all users
GET http://localhost:3003/api/users

### POST to create a new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "root",
  "password": "opensesame",
  "name": "David Brent"
}

### username too short
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "pi",
  "password": "pw1",
  "name": "Bella Ching"
}

### password too short
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "username1",
  "password": "pw",
  "name": "Bella Ching"
}

#************TOKENS*****************
### successful login to get token
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "root",
  "password": "opensesame"
}

### unsuccessful login - no such user
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "aji233",
  "password": "289sadf"
}

### unsuccessful login - incorrect password
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "root",
  "password": "opensesame-plusextra"
}