########## LOCALHOST ##########

### Get all entries
GET http://localhost:3001/api/persons

### Get info (# phonebook entries, timestamp)
GET http://localhost:3001/info

### Get single entry
GET http://localhost:3001/api/persons/66b26d27ea8b1a8fe3c51eda

### Delete single entry
DELETE http://localhost:3001/api/persons/66b26d27ea8b1a8fe3c51eda

### Add a single entry correctly
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Alan Turing", 
  "number": "56-78-910111"
}

### Fail to add a single entry - name missing
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "12345"
}

### Fail to add a single entry - number missing
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Don Knuth"
}

### Fail to add a single entry - name not unique
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Alan Turing", 
  "number": "56-78-910111"
}

### Update an existing name with new number
PUT http://localhost:3001/api/persons/66b4ec0e5d1097490942cf45
Content-Type: application/json

{
  "name": "person99",
  "number": "555"
}

### Fail to add a single entry - name too short
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "ab", 
  "number": "911"
}

### Fail to update an existing name with new number b/c new name too short
PUT http://localhost:3001/api/persons/66b4ec0e5d1097490942cf45
Content-Type: application/json

{
  "name": "a",
  "number": "555"
}

########## fly.io ##########
### Get all entries
GET https://phonebook-silent-mountain-480.fly.dev/api/persons

### Get info (# phonebook entries, timestamp)
GET https://phonebook-silent-mountain-480.fly.dev/info

### Get single entry
GET https://phonebook-silent-mountain-480.fly.dev/api/persons/3

### Delete single entry
DELETE https://phonebook-silent-mountain-480.fly.dev/api/persons/3

### Add a single entry correctly
POST https://phonebook-silent-mountain-480.fly.dev/api/persons
Content-Type: application/json

{
  "name": "Alan Turing", 
  "number": "56-78-910111"
}

### Fail to add a single entry - name missing
POST https://phonebook-silent-mountain-480.fly.dev/api/persons
Content-Type: application/json

{
  "number": "12345"
}

### Fail to add a single entry - number missing
POST https://phonebook-silent-mountain-480.fly.dev/api/persons
Content-Type: application/json

{
  "name": "Don Knuth"
}

### Fail to add a single entry - name not unique
POST https://phonebook-silent-mountain-480.fly.dev/api/persons
Content-Type: application/json

{
  "name": "Alan Turing", 
  "number": "56-78-910111"
}