########## LOCALHOST ##########

### Get all entries
GET https://phonebook-silent-mountain-480.fly.dev/api/persons

### Get info (# phonebook entries, timestamp)
GET https://phonebook-silent-mountain-480.fly.dev/info

### Get single entry
GET https://phonebook-silent-mountain-480.fly.dev/api/persons/3

### Delete single entry
DELETE https://phonebook-silent-mountain-480.fly.dev/api/persons/3

### Add a single entry correctly
POST https://phonebook-silent-mountain-480.fly.dev/api/persons
Content-Type: application/json

{
  "name": "Alan Turing", 
  "number": "56-78-910111"
}

### Fail to add a single entry - name missing
POST https://phonebook-silent-mountain-480.fly.dev/api/persons
Content-Type: application/json

{
  "number": "12345"
}

### Fail to add a single entry - number missing
POST https://phonebook-silent-mountain-480.fly.dev/api/persons
Content-Type: application/json

{
  "name": "Don Knuth"
}

### Fail to add a single entry - name not unique
POST https://phonebook-silent-mountain-480.fly.dev/api/persons
Content-Type: application/json

{
  "name": "Alan Turing", 
  "number": "56-78-910111"
}

########## fly.io ##########
### Get all entries
GET https://phonebook-silent-mountain-480.fly.dev/api/persons

### Get info (# phonebook entries, timestamp)
GET https://phonebook-silent-mountain-480.fly.dev/info

### Get single entry
GET https://phonebook-silent-mountain-480.fly.dev/api/persons/3

### Delete single entry
DELETE https://phonebook-silent-mountain-480.fly.dev/api/persons/3

### Add a single entry correctly
POST https://phonebook-silent-mountain-480.fly.dev/api/persons
Content-Type: application/json

{
  "name": "Alan Turing", 
  "number": "56-78-910111"
}

### Fail to add a single entry - name missing
POST https://phonebook-silent-mountain-480.fly.dev/api/persons
Content-Type: application/json

{
  "number": "12345"
}

### Fail to add a single entry - number missing
POST https://phonebook-silent-mountain-480.fly.dev/api/persons
Content-Type: application/json

{
  "name": "Don Knuth"
}

### Fail to add a single entry - name not unique
POST https://phonebook-silent-mountain-480.fly.dev/api/persons
Content-Type: application/json

{
  "name": "Alan Turing", 
  "number": "56-78-910111"
}